name = "9bench"
compatibility_date = "2026-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "9bench-results"
database_id = "23d447b4-c489-4ac7-bfe2-ff39105feae0"
